server:
  #端口
  port: 8080
  #配置https访问 项目上线时启用
#  ssl:
#    key-store: classpath:6661544_fengxian.yandage.top.pfx
#    key-store-password: zNWqegoh
#    key-store-type: PKCS12
spring:
  #数据源
  datasource:
    url: jdbc:mysql://47.101.223.63:13457/hg_volunteer?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: lfy123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  #Redis
  redis:
    host: 47.101.223.63
    port: 6379
    password: volunteer
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
  ##发送qq邮件配置
  mail:
    ##邮箱服务器地址
    host: smtp.qq.com
    port: 25
    username: 2062728920@qq.com #发送方邮箱
    password: aijaryfrfvdseegd #smtp口令
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
          starttls.required: true
          socketFactory.class: javax.net.ssl.SSLSocketFactor
mail:
  fromMail:
    addr: fengyuan-liang

logging:
  level:
    com.volunteer.mapper: debug

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.volunteer.entity
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1 # 逻辑删除，已删除
      logic-not-delete-value: 0 # 逻辑删除，未删除
  configuration:
    #下划线转驼峰配置
    map-underscore-to-camel-case: true


# ===================================================================
# 分布式文件系统FDFS配置
# ===================================================================
fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image:             #缩略图生成参数159x150
    width: 150
    height: 150
  tracker-list:            #TrackerList参数,支持多个
    - 47.101.206.1:22122

#阿里云oss对象存储系统配置
oss:
  endpoint: oss-cn-beijing.aliyuncs.com
  accessKeyId: LTAI5tFfKdKLXjUE7wPgekaT
  accessKeySecret: S3Ubgng97xUNrt0xSw2cQUEpIVPxtL
  bucketName: lfy-hg-volunteer
  bucketDomain: https://lfy-hg-volunteer.oss-cn-beijing.aliyuncs.com/

#云服务器的配置信息
vm:
  host: 47.101.206.1
  nginx-port: 8080

#小程序的配置信息
mini-program:
#  appId: wx7fb72aa57c11f260
#  appSecret: ffd2811e2bb4deb45e1fbca8a897d870
  appId: wx93c0ea617266b2e7
  appSecret: e670ef525dfc30ffa54f610bbafd3409


#腾讯云的配置信息
tencent-cloud:
  secretId: AKIDCDxRfcIhpgGZbNt86oFQKyKPDk0zg6G9
  secretKey: e18yXprc6JFuIPFp8AvRgeLktlMgkX3I
  #短信SdkAppId在 [短信控制台] 添加应用后生成的实际SdkAppId
  sdkAppId: 1400613395
  #短信签名，短信【】中的内容
  signName: VernHe
  #短信模板ID
  templateId: 1248012
  #验证码的有效期,单位是分钟
  expires: 3

##用户AES加密密钥
AES-secret: aEsva0zDHECg47P8SuPzmw==

#线程池的配置
task:
  pool:
    corePoolSize: 5 #设置核心线程数
    maxPoolSize: 10  #设置最大线程数
    keepAliveSeconds: 300 #设置线程活跃时间（秒）
    queueCapacity: 50 #设置队列容量
    threadNamePrefix: thread-pool-service-
##xxl-job配置
xxl:
  job:
    admin:
      addresses: http://127.0.0.1:8081/xxl-job-admin #部署的调度中心的url
    executor:
      appname: xxl-job-volunteer-executor #执行器的名字
      ip:
      port: 9999 #调度中心调用执行器时使用的端口
      logpath: /data/apploggs/xxl-job/jobhandler #日志路径
      logretentiondays: 30 #日志保留天数
    accessToken:

#xxl:
#  job:
#    login:
#      username: admin
#      password: 123456
#    #调度中心部署跟地址：如调度中心集群部署存在多个地址则用逗号分隔。
#    #执行器将会使用该地址进行"执行器心跳注册"和"任务结果回调"。
#    ### xxl-job admin address list, such as "http://address" or "http://address01,http://address02"
#    admin:
#      addresses: http://127.0.0.1:8080/xxl-job-admin
#    #分别配置执行器的名称、ip地址、端口号
#    #注意：如果配置多个执行器时，防止端口冲突
#    executor:
#      appname: executorDemo
#      ip: 127.0.0.1
#      port: 9999
#      #执行器运行日志文件存储的磁盘位置，需要对该路径拥有读写权限
#      logpath: /data/applogs/xxl-job/jobhandler
#      #执行器Log文件定期清理功能，指定日志保存天数，日志文件过期自动删除。限制至少保持3天，否则功能不生效；
#      #-1表示永不删除
#      logretentiondays: 30
#    #执行器通讯TOKEN：非空时启用
#    ### xxl-job, access token
#    accessToken: ""
#    ## 调度线程池最大线程配置【必填】
#    triggerpool:
#      fast:
#        max: 200
#      slow:
#        max: 100
#    ### 调度中心国际化配置 [必填]： 默认为 "zh_CN"/中文简体, 可选范围为 "zh_CN"/中文简体, "zh_TC"/中文繁体 and "en"/英文；
#    i18n: zh_CN