server:
  #??
  port: 8080

spring:
  #?????
  datasource:
    url: jdbc:mysql://47.101.206.1:3306/hg_volunteer?useUnicode=true&characterEncoding=utf-8
    username: admin
    password: mypass
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  #Redis
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0


mybatis:
  #MyBatis
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.volunteer.entity

logging:
  level:
    com.volunteer.mapper: debug

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1 # ??????(??? 1)
      logic-not-delete-value: 0 # ??????(??? 0)

