server:
  #端口
  port: 8080

spring:
  #数据源
  datasource:
    url: jdbc:mysql://47.101.206.1:3306/hg_volunteer?useUnicode=true&characterEncoding=utf-8
    username: admin
    password: mypass
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  #Redis
  redis:
    host: 47.101.206.1
    port: 6379
    password: volunteer
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
  #RabbitMQ
#  rabbitmq:
#    username: vernhe  #用户名
#    password: vernhe  #密码
#    host: 192.168.220.220
#    port: 5672
#    virtual-host: /xzk

logging:
  level:
    com.volunteer.mapper: debug

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.volunteer.entity
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1 # 逻辑删除，已删除
      logic-not-delete-value: 0 # 逻辑删除，未删除
  configuration:
    #下划线转驼峰配置
    map-underscore-to-camel-case: true


# ===================================================================
# 分布式文件系统FDFS配置
# ===================================================================
fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image:             #缩略图生成参数159x150
    width: 150
    height: 150
  tracker-list:            #TrackerList参数,支持多个
    - 47.101.206.1:22122

#云服务器的配置信息
vm:
  host: 47.101.206.1
  nginx-port: 8080

#小程序的配置信息
mini-program:
  appId: wx7fb72aa57c11f260
  appSecret: ffd2811e2bb4deb45e1fbca8a897d870
#  appId: wx93c0ea617266b2e7
#  appSecret: e670ef525dfc30ffa54f610bbafd3409


#腾讯云的配置信息
tencent-cloud:
  secretId: AKIDCDxRfcIhpgGZbNt86oFQKyKPDk0zg6G9
  secretKey: e18yXprc6JFuIPFp8AvRgeLktlMgkX3I
  #短信SdkAppId在 [短信控制台] 添加应用后生成的实际SdkAppId
  sdkAppId: 1400613395
  #短信签名，短信【】中的内容
  signName: VernHe
  #短信模板ID
  templateId: 1248012
  #验证码的有效期,单位是分钟
  expires: 3

##用户AES加密密钥
AES-secret: aEsva0zDHECg47P8SuPzmw==

#线程池的配置
task:
  pool:
    corePoolSize: 5 #设置核心线程数
    maxPoolSize: 10  #设置最大线程数
    keepAliveSeconds: 300 #设置线程活跃时间（秒）
    queueCapacity: 50 #设置队列容量
    threadNamePrefix: thread-pool-service-
