server:
  #端口
  port: 8080
  #配置https访问 项目上线时启用
  ssl:
    key-store: classpath:7202264_volunteer.fengxianhub.top.pfx
    key-store-password: JS9jg38H
    key-store-type: PKCS12
spring:
  #数据源
  datasource:
    url: jdbc:mysql://47.101.223.63:13457/hg_volunteer?useUnicode=true&useSSL=false&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useAffectedRows=true&allowMultiQueries=true
    username: root
    password: lfy123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    #初始化大小
    initialSize: 5
    #最小值
    minIdle: 5
    #最大值
    maxActive: 20
    #最大等待时间，配置获取连接等待超时，时间单位都是毫秒ms
    maxWait: 60000
    #配置间隔多久才进行一次检测，检测需要关闭的空闲连接
    timeBetweenEvictionRunsMillis: 60000
    #配置一个连接在池中最小生存的时间
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，
    #'wall'用于防火墙，SpringBoot中没有log4j，我改成了log4j2
    filters: stat,wall,slf4j
    #最大PSCache连接
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  #Redis
  redis:
    host: 47.101.223.63
    port: 6379
    password: volunteer
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
  ##发送qq邮件配置
  mail:
    ##邮箱服务器地址
    host: smtp.qq.com
    # 非ssl 25  ssl 587
    port: 587
    username: 2062728920@qq.com #发送方邮箱
    password: aijaryfrfvdseegd #smtp口令
    mailFromNick: 计算机青协 #发件人昵称
    default-encoding: UTF-8
    #使用ssl通道发送qq邮件
    properties:
      mail:
        smtp:
          socketFactory:
            class=javax:
              net:
                ssl:
                  SSLSocketFactory:
          auth: true
          starttls:
            enable: true
            required: true
  servlet:
    multipart:
      max-file-size: 10MB #设置文件上传大小上线为10M 默认1M
#配置swagger的账号密码
knife4j:
  # 开启增强配置
  enable: true
  basic:
    enable: true
    # Basic认证用户名
    username: volunteer
    # Basic认证密码
    password: volunteer

mail:
  fromMail:
    addr: fengyuan-liang

logging:
  level:
    com.volunteer.mapper: debug
  #  在当前项目下生成日志文件
  file:
    path: /var/log/volunteer
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.volunteer.entity
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1 # 逻辑删除，已删除
      logic-not-delete-value: 0 # 逻辑删除，未删除

#阿里云oss对象存储系统配置
oss:
  endpoint: oss-cn-beijing.aliyuncs.com
  accessKeyId: LTAI5tFfKdKLXjUE7wPgekaT
  accessKeySecret: S3Ubgng97xUNrt0xSw2cQUEpIVPxtL
  bucketName: lfy-hg-volunteer
  bucketDomain: https://lfy-hg-volunteer.oss-cn-beijing.aliyuncs.com/
  myOssUrl: https://www.volunteer.fengxianhub.top/ #绑定oss的域名，让图片可以直接访问到
#云服务器的配置信息
vm:
  host: 47.101.206.1
  nginx-port: 8080

#小程序的配置信息
mini-program:
#  appId: wx7fb72aa57c11f260
#  appSecret: ffd2811e2bb4deb45e1fbca8a897d870
  appId: wx93c0ea617266b2e7
  appSecret: e670ef525dfc30ffa54f610bbafd3409


#腾讯云的配置信息
tencent-cloud:
  secretId: AKIDCDxRfcIhpgGZbNt86oFQKyKPDk0zg6G9
  secretKey: e18yXprc6JFuIPFp8AvRgeLktlMgkX3I
  #短信SdkAppId在 [短信控制台] 添加应用后生成的实际SdkAppId
  sdkAppId: 1400613395
  #短信签名，短信【】中的内容
  signName: VernHe
  #短信模板ID
  templateId: 1248012
  #验证码的有效期,单位是分钟
  expires: 3

##用户AES加密密钥
AES-secret: aEsva0zDHECg47P8SuPzmw==

#线程池的配置
task:
  pool:
    corePoolSize: 5 #设置核心线程数
    maxPoolSize: 10  #设置最大线程数
    keepAliveSeconds: 300 #设置线程活跃时间（秒）
    queueCapacity: 50 #设置队列容量
    threadNamePrefix: thread-pool-service-
##xxl-job配置
xxl:
  job:
    admin:
      addresses: https://volunteer.fengxianhub.top:8081/xxl-job-admin #部署的调度中心的url
    executor:
      appname: xxl-job-volunteer-executor #执行器的名字
      ip:
      port: 9999 #调度中心调用执行器时使用的端口
      logpath: /data/apploggs/xxl-job/jobhandler #日志路径
      logretentiondays: 30 #日志保留天数
    accessToken:

##爱心雨伞默认数据
umbrella:
  umbrellaBorrowRecordPageSize: 20 #爱心雨伞借阅记录默认返回条数
  defaultBorrowDuration: 48 #默认用户能够借取雨伞的时间为24小时
  defaultUnlockWaitTime: 14 #爱心雨伞锁机默认开锁时间 单位秒,这里要考虑数据延迟的时间，所以校正误差时间四秒钟
Kcp:
  port: 67 #锁机与服务器通信端口
